spring:
  application:
    name: service-module-video
server:
  port: 9000


accesskey: iK_pM9aLioR5k3tB_r2oYNuerxn_hA8kcyE8PBiX
secretkey: JFwZbldp7sDzAxvxTJSD2yB7-tUdiuLKsEGlsqoi
bucket: picture_server
cdns: popf2cli9.bkt.clouddn.com