server:
  port: 8010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK/0YWAoLWtrRcqA5NnmgxRmeyWRSnZzyxCWYWxHm9qk4LxtpyLNz1OkkYuTdUajbERuN1L68S0xHewVNv6elOcCAwEAAQ==
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hergua.cn:3306/mall
    username: server
    password: AoRPgnVxlq60xigEUw8SuTBRbH6GGhlkoA5NqIM/tIZshfW3nrXiSst85lIkpZ/o6vztM74V3D3Atb137beDwQ==
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 1
      min-idle: 3
      max-idle: 20
      max-wait-millis: 60000
      # disconnect after 60000 millions without action
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # specified every PSCache's size
      pool-prepared-statements: true
      max-open-prepared-statements: 20
    druid:
      filters: config
      connection-properties: config.decrypt=true;config.decrypt.key=${publickey}
  http:
    encoding:
      charset: utf-8
    converters:
      preferred-json-mapper: jackson